/******************************************************************************
* Error Definition <ErrorDefinition.h>:
* This header is used for storing all types of errors and their relaitonships,
* this design allows for an easy lookup of all error codes and their
* descriptions
* CSS502 - Assignment 3
* University of Washington - Winter 2013
* Hugo Belin Melgoza
******************************************************************************/

#ifndef ERRORDEF_H
#define ERRORDEF_H

#define ERROR_1 "-> ERROR: Invalid resource identifier"
#define ERROR_2 "-> ERROR: String cannot be converted to integer"
#define ERROR_3 "-> ERROR: User Id does not comply with length requirements"
#define ERROR_4 "-> ERROR: Input cannot be null"
#define ERROR_5 "-> ERROR: String command cannot be empty"
#define ERROR_6 "-> ERROR: String branchId cannot be empty"
#define ERROR_7 "-> ERROR: String library cannot be empty"
#define ERROR_8 "-> ERROR: Invalid user name"
#define ERROR_9 "-> ERROR: Invalid type in resource command"
#define ERROR_10 "-> ERROR: Integer cannot be less than 0"
#define ERROR_11 "-> ERROR: Integer month is not between 1 and 12"
#define ERROR_12 "-> ERROR: String title cannot be empty"
#define ERROR_13 "-> ERROR: Command has missing data title/author, title/genre"
#define ERROR_14 "-> ERROR: Object cannot be null"
#define ERROR_15 "-> ERROR: Library object already on libraries HashTable"
#define ERROR_16 "-> ERROR: String key cannot be empty"
#define ERROR_17 "-> ERROR: HashTable Object* value cannot be NULL"
#define ERROR_18 "-> ERROR: Value already exists in HashTable"
#define ERROR_19 "-> ERROR: HashTable is empty"
#define ERROR_20 "-> ERROR: Selected Library does not exist in hash table"
#define ERROR_21 "-> ERROR: This object has not been initialized"
#define ERROR_22 "-> ERROR: Parameter object has not been initialized"
#define ERROR_23 "-> ERROR: String userId cannot be empty"
#define ERROR_24 "-> ERROR: Invalid user construction string"
#define ERROR_25 "-> ERROR: Resource has no available copies"
#define ERROR_26 "-> ERROR: UserId did not checkout this resource previously"
#define ERROR_27 "-> ERROR: Resource has no checked copies"
#define ERROR_28 "-> ERROR: Resource is already checked out to this user ID"
#define ERROR_29 "-> ERROR: Parameter is not supported in this resource"
#define ERROR_30 "-> ERROR: Resource code is not yet implemented by hash function"
#define ERROR_31 "-> ERROR: Invalid resource construction string"
#define ERROR_32 "-> ERROR: Invalid action command"
#define ERROR_33 "-> ERROR: String cannot be empty"
#define ERROR_34 "-> ERROR: Invalid resource format, only supported Hard Copy"
#define ERROR_35 "-> ERROR: This user does not have archived history"
#define ERROR_36 "-> ERROR: User cannot be NULL"
#define ERROR_37 "-> ERROR: Resource cannot be NULL"
#define ERROR_38 "-> ERROR: Invalid transaction code"
#define ERROR_39 "-> ERROR: User is not registered in library"
#define ERROR_40 "-> ERROR: Resource does not exist"
#define ERROR_41 "-> ERROR: ResourceCollection cannot be NULL"

// Fata Errors, errors that should not occur
#define FATAL_ERROR1 "-> FATAL ERROR: Duplicate key not caught by HashTable::Retrieve"
#define FATAL_ERROR2 "-> FATAL ERROR: End of trie is not null"
#define FATAL_ERROR3 "-> FATAL ERROR: Undefined HashTable type"

// Method ids
#define MID_1 "bool Library::parseResource(string command)"
#define MID_2 "bool Library::parseUser(string command)"
#define MID_3 "bool LibraryManager::parseResource(string library, ifstream &input)"
#define MID_4 "bool LibraryManager::parseResource(string library, string command)"
#define MID_5 "bool LibraryManager::parseUser(string library, ifstream &input)"
#define MID_6 "bool LibraryManager::parseUser(string library, string command)"
#define MID_7 "bool LibraryManager::parseCommand(string library, ifstream &input)"
#define MID_8 "bool LibraryManager::parseCommand(string library, string command)"
#define MID_9 "bool LibraryManager::AddBranch(string branchId)"
#define MID_10 "bool Library::parseResource(ifstream &input)"
#define MID_11 "bool Library::parseUser(ifstream &input)"
#define MID_12 "bool Library::operator==(const Object &obj) const"
#define MID_13 "bool Library::operator!=(const Object &obj) const"
#define MID_14 "bool Library::operator<(const Object &obj) const"
#define MID_15 "bool Library::operator<=(const Object &obj)const"
#define MID_16 "bool Library::operator>(const Object &obj) const"
#define MID_17 "bool Library::operator>=(const Object &obj) const"
#define MID_18 "Object* HashTable::operator[](string key) const"
#define MID_19 "Object* HashTable::retrieve(string key) const"
#define MID_20 "Object* HashTable::remove(string key)"
#define MID_21 "bool HashTable::add(std::string key, const Object* value)"
#define MID_22 "bool Patron::operator==(const Object &obj) const"
#define MID_23 "bool Patron::operator!=(const Object &obj) const"
#define MID_24 "bool Patron::operator<(const Object &obj) const"
#define MID_25 "bool Patron::operator<=(const Object &obj) const"
#define MID_26 "bool Patron::operator>(const Object &obj) const"
#define MID_27 "bool Patron::operator>=(const Object &obj) const"
#define MID_28 "bool Librarian::operator==(const Object &obj) const"
#define MID_29 "bool Librarian::operator!=(const Object &obj) const"
#define MID_30 "bool Librarian::operator<(const Object &obj) const"
#define MID_31 "bool Librarian::operator<=(const Object &obj) const"
#define MID_32 "bool Librarian::operator>(const Object &obj) const"
#define MID_33 "bool Librarian::operator>=(const Object &obj) const"
#define MID_34 "string UserCollection::userHash(string userId) const"
#define MID_35 "bool UserCollection::addUser(string cmd)"
#define MID_36 "bool HashTable::operator==(const Object &obj) const"
#define MID_37 "bool HashTable::operator!=(const Object &obj) const"
#define MID_38 "bool HashTable::operator<(const Object &obj) const"
#define MID_39 "bool HashTable::operator<=(const Object &obj) const"
#define MID_40 "bool HashTable::operator>(const Object &obj) const"
#define MID_41 "bool HashTable::operator>=(const Object &obj) const"
#define MID_42 "bool UserCollection::addUser(string cmd)"
#define MID_43 "User* UserCollection::getUser(string userId) const"
#define MID_44 "bool Fiction::operator==(const Object &obj) const"
#define MID_45 "bool Fiction::operator!=(const Object &obj) const"
#define MID_46 "bool Fiction::operator<(const Object &obj) const"
#define MID_47 "bool Fiction::operator<=(const Object &obj) const"
#define MID_48 "bool Fiction::operator>(const Object &obj) const"
#define MID_49 "bool Fiction::operator>=(const Object &obj) const"
#define MID_50 "string Fiction::populate(string cmd)"
#define MID_51 "string Fiction::getKey() const"
#define MID_52 "bool Fiction::returnResource(string userId)"
#define MID_53 "bool Fiction::checkoutResource(string userId)"
#define MID_54 "string Fiction::getMonth() const"
#define MID_55 "string Fiction::getGenre() const"
#define MID_56 "bool Youth::operator==(const Object &obj) const"
#define MID_57 "bool Youth::operator!=(const Object &obj) const"
#define MID_58 "bool Youth::operator<(const Object &obj) const"
#define MID_59 "bool Youth::operator<=(const Object &obj) const"
#define MID_60 "bool Youth::operator>(const Object &obj) const"
#define MID_61 "bool Fiction::operator>=(const Object &obj) const"
#define MID_62 "string Youth::populate(string cmd)"
#define MID_63 "string Youth::getMonth() const"
#define MID_64 "string Youth::getGenre() const"
#define MID_65 "bool Youth::returnResource(string userId)"
#define MID_66 "bool Youth::checkoutResource(string userId)"
#define MID_67 "string Youth::getKey() const"
#define MID_68 "bool Periodical::operator==(const Object &obj) const"
#define MID_69 "bool Periodical::operator!=(const Object &obj) const"
#define MID_70 "bool Periodical::operator<(const Object &obj) const"
#define MID_71 "bool Periodical::operator<=(const Object &obj) const"
#define MID_72 "bool Periodical::operator>(const Object &obj) const"
#define MID_73 "bool Periodical::operator>=(const Object &obj) const"
#define MID_74 "string Periodical::populate(string cmd)"
#define MID_75 "string Periodical::getAuthor() const"
#define MID_76 "string Periodical::getGenre() const"
#define MID_77 "bool Periodical::returnResource(string userId)"
#define MID_78 "bool Periodical::checkoutResource(string userId)"
#define MID_79 "string Periodical::getKey() const"
#define MID_80 "bool Video::operator==(const Object &obj) const"
#define MID_81 "bool Video::operator!=(const Object &obj) const"
#define MID_82 "bool Video::operator<(const Object &obj) const"
#define MID_83 "bool Video::operator<=(const Object &obj) const"
#define MID_84 "bool Video::operator>(const Object &obj) const"
#define MID_85 "bool Video::operator>=(const Object &obj) const"
#define MID_86 "string Video::populate(string cmd)"
#define MID_87 "string Video::getMonth() const"
#define MID_88 "string Video::getAuthor() const"
#define MID_89 "bool Video::returnResource(string userId)"
#define MID_90 "bool Video::checkoutResource(string userId)"
#define MID_91 "string Video::getKey() const"
#define MID_92 "bool Audio::operator==(const Object &obj) const"
#define MID_93 "bool Audio::operator!=(const Object &obj) const"
#define MID_94 "bool Audio::operator<(const Object &obj) const"
#define MID_95 "bool Audio::operator<=(const Object &obj) const"
#define MID_96 "bool Audio::operator>(const Object &obj) const"
#define MID_97 "bool Audio::operator>=(const Object &obj) const"
#define MID_98 "string Audio::populate(string cmd)"
#define MID_99 "string Audio::getMonth() const"
#define MID_100 "string Audio::getAuthor() const"
#define MID_101 "bool Audio::returnResource(string userId)"
#define MID_102 "bool Audio::checkoutResource(string userId)"
#define MID_103 "string ResourceCollection::resourceHash(string resourceId) const"
#define MID_104 "bool ResourceCollection::addResource(string resource)"
#define MID_105 "bool Library::parseCommand(string command)"
#define MID_106 "Resource* ResourceCollection::getResource(string resource)"
#define MID_107 "string Library::fixString(string resource) const"
#define MID_108 "void User::printHistory() const"
#define MID_109 "bool Transaction::operator==(const Object &obj) const"
#define MID_110 "bool Transaction::operator!=(const Object &obj) const"
#define MID_111 "bool Transaction::operator<(const Object &obj) const"
#define MID_112 "bool Transaction::operator<=(const Object &obj) const"
#define MID_113 "bool Transaction::operator>(const Object &obj) const"
#define MID_114 "bool Transaction::operator>=(const Object &obj) const"
#define MID_115 "void PrintHistory::Execute(string cmd, User *user, Resource *resource, ResourceCollection *resourceCollection) const"
#define MID_116 "void CheckoutTransaction::Execute(string cmd, User *user, Resource *resource, ResourceCollection *res) const "
#define MID_117 "void ReturnResource::Execute(string cmd, User *user, Resource *resource, ResourceCollection *resourceCollection) const"
#define MID_118 "void TransactionCollection::Execute(string cmd, User *user, Resource *resource, ResourceCollection *resourceCollection)"
#define MID_119 "void DisplayTransaction::Execute(string cmd, User *user, Resource *resource, ResourceCollection *res) const"
#define MID_120 "void ResourceCollection::print() const"

// Some notes
#define NOTE1 "+ 1 accounts for the space following the word"

#endif
